"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { folioSchema } from "@/lib/validations/folios";
import { z } from "zod";
import type { ActionState } from "@/types/actions";

// ── Create Folio ──────────────────────────────────────────────

export async function createFolio(
  _prevState: ActionState | null,
  formData: FormData
): Promise<ActionState> {
  // 1. Verify admin role
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // 2. Validate with Zod
  const rawData = {
    sucursal_id: formData.get("sucursal_id"),
    cliente_id: formData.get("cliente_id"),
    descripcion_problema: formData.get("descripcion_problema"),
  };

  const result = folioSchema.safeParse(rawData);
  if (!result.success) {
    const flattened = z.flattenError(result.error);
    return { fieldErrors: flattened.fieldErrors };
  }

  // 3. Validate user assignment
  const userIds = formData.getAll("usuarios") as string[];
  if (userIds.length === 0) {
    return { error: "Debe asignar al menos un tecnico al folio" };
  }

  // 4. Insert folio (numero_folio auto-generated by DB trigger)
  const { data: folio, error: folioError } = await supabase
    .from("folios")
    .insert({
      sucursal_id: result.data.sucursal_id,
      cliente_id: result.data.cliente_id,
      descripcion_problema: result.data.descripcion_problema,
    })
    .select("id")
    .single();

  if (folioError) {
    return { error: "Error al crear el folio: " + folioError.message };
  }

  // 5. Insert user assignments
  const assignments = userIds.map((uid) => ({
    folio_id: folio.id,
    usuario_id: uid,
  }));

  const { error: assignError } = await supabase
    .from("folio_asignados")
    .insert(assignments);

  if (assignError) {
    return {
      error:
        "El folio fue creado pero hubo un error al asignar usuarios: " +
        assignError.message,
    };
  }

  // 6. Insert equipment assignments
  const equipoIds = formData.getAll("equipos") as string[];
  if (equipoIds.length > 0) {
    const equipoAssignments = equipoIds.map((eid) => ({
      folio_id: folio.id,
      equipo_id: eid,
      added_by: user.id,
    }));

    const { error: equipoError } = await supabase
      .from("folio_equipos")
      .insert(equipoAssignments);

    if (equipoError) {
      return {
        error:
          "El folio fue creado pero hubo un error al asignar equipos: " +
          equipoError.message,
      };
    }
  }

  // 7. Revalidate and redirect
  revalidatePath("/admin/folios");
  redirect("/admin/folios");
}

// ── Update Folio ──────────────────────────────────────────────

export async function updateFolio(
  id: string,
  _prevState: ActionState | null,
  formData: FormData
): Promise<ActionState> {
  // 1. Verify admin role
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // 2. Validate with Zod
  const rawData = {
    sucursal_id: formData.get("sucursal_id"),
    cliente_id: formData.get("cliente_id"),
    descripcion_problema: formData.get("descripcion_problema"),
  };

  const result = folioSchema.safeParse(rawData);
  if (!result.success) {
    const flattened = z.flattenError(result.error);
    return { fieldErrors: flattened.fieldErrors };
  }

  // 3. Validate user assignment
  const userIds = formData.getAll("usuarios") as string[];
  if (userIds.length === 0) {
    return { error: "Debe asignar al menos un tecnico al folio" };
  }

  // 4. Update folio table
  const { error: updateError } = await supabase
    .from("folios")
    .update({
      sucursal_id: result.data.sucursal_id,
      cliente_id: result.data.cliente_id,
      descripcion_problema: result.data.descripcion_problema,
    })
    .eq("id", id);

  if (updateError) {
    return {
      error: "Error al actualizar el folio: " + updateError.message,
    };
  }

  // 5. Reassign users: delete existing, insert new
  const { error: deleteError } = await supabase
    .from("folio_asignados")
    .delete()
    .eq("folio_id", id);

  if (deleteError) {
    return {
      error:
        "Error al actualizar asignaciones: " + deleteError.message,
    };
  }

  const assignments = userIds.map((uid) => ({
    folio_id: id,
    usuario_id: uid,
  }));

  const { error: assignError } = await supabase
    .from("folio_asignados")
    .insert(assignments);

  if (assignError) {
    return {
      error:
        "El folio fue actualizado pero hubo un error al reasignar usuarios: " +
        assignError.message,
    };
  }

  // 6. Reassign equipment: delete existing, insert new
  const { error: deleteEquipoError } = await supabase
    .from("folio_equipos")
    .delete()
    .eq("folio_id", id);

  if (deleteEquipoError) {
    return {
      error:
        "Error al actualizar equipos: " + deleteEquipoError.message,
    };
  }

  const equipoIds = formData.getAll("equipos") as string[];
  if (equipoIds.length > 0) {
    const equipoAssignments = equipoIds.map((eid) => ({
      folio_id: id,
      equipo_id: eid,
      added_by: user.id,
    }));

    const { error: equipoError } = await supabase
      .from("folio_equipos")
      .insert(equipoAssignments);

    if (equipoError) {
      return {
        error:
          "El folio fue actualizado pero hubo un error al reasignar equipos: " +
          equipoError.message,
      };
    }
  }

  // 7. Revalidate and redirect
  revalidatePath("/admin/folios");
  redirect("/admin/folios");
}

// ── Add Equipment to Folio ──────────────────────────────────────

export async function addEquipmentToFolio(
  folioId: string,
  equipoId: string
): Promise<ActionState> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  const { error } = await supabase
    .from("folio_equipos")
    .upsert(
      { folio_id: folioId, equipo_id: equipoId, added_by: user.id },
      { onConflict: "folio_id,equipo_id" }
    );

  if (error) {
    return { error: "Error al agregar equipo al folio: " + error.message };
  }

  revalidatePath(`/admin/folios/${folioId}`);
  return { success: true, message: "Equipo agregado al folio" };
}

// ── Remove Equipment from Folio ─────────────────────────────────

export async function removeEquipmentFromFolio(
  folioId: string,
  equipoId: string
): Promise<ActionState> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // Check if equipment has report entries under this folio
  const { data: reportEntries } = await supabase
    .from("reporte_equipos")
    .select("id, reportes!inner(folio_id)")
    .eq("equipo_id", equipoId)
    .eq("reportes.folio_id", folioId)
    .limit(1);

  if (reportEntries && reportEntries.length > 0) {
    return {
      error:
        "No se puede quitar este equipo porque tiene reportes asociados en este folio.",
    };
  }

  const { error } = await supabase
    .from("folio_equipos")
    .delete()
    .eq("folio_id", folioId)
    .eq("equipo_id", equipoId);

  if (error) {
    return { error: "Error al quitar equipo del folio: " + error.message };
  }

  revalidatePath(`/admin/folios/${folioId}`);
  return { success: true, message: "Equipo quitado del folio" };
}
