"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { folioSchema } from "@/lib/validations/folios";
import { z } from "zod";
import type { ActionState } from "@/types/actions";

// ── Create Folio ──────────────────────────────────────────────

export async function createFolio(
  _prevState: ActionState | null,
  formData: FormData
): Promise<ActionState> {
  // 1. Verify admin role
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // 2. Validate with Zod
  const rawData = {
    sucursal_id: formData.get("sucursal_id"),
    cliente_id: formData.get("cliente_id"),
    descripcion_problema: formData.get("descripcion_problema"),
  };

  const result = folioSchema.safeParse(rawData);
  if (!result.success) {
    const flattened = z.flattenError(result.error);
    return { fieldErrors: flattened.fieldErrors };
  }

  // 3. Validate user assignment
  const userIds = formData.getAll("usuarios") as string[];
  if (userIds.length === 0) {
    return { error: "Debe asignar al menos un tecnico al folio" };
  }

  // 4. Insert folio (numero_folio auto-generated by DB trigger)
  const { data: folio, error: folioError } = await supabase
    .from("folios")
    .insert({
      sucursal_id: result.data.sucursal_id,
      cliente_id: result.data.cliente_id,
      descripcion_problema: result.data.descripcion_problema,
    })
    .select("id")
    .single();

  if (folioError) {
    return { error: "Error al crear el folio: " + folioError.message };
  }

  // 5. Insert user assignments
  const assignments = userIds.map((uid) => ({
    folio_id: folio.id,
    usuario_id: uid,
  }));

  const { error: assignError } = await supabase
    .from("folio_asignados")
    .insert(assignments);

  if (assignError) {
    // Folio was created but assignment failed — partial success
    return {
      error:
        "El folio fue creado pero hubo un error al asignar usuarios: " +
        assignError.message,
    };
  }

  // 6. Revalidate and redirect
  revalidatePath("/admin/folios");
  redirect("/admin/folios");
}

// ── Update Folio ──────────────────────────────────────────────

export async function updateFolio(
  id: string,
  _prevState: ActionState | null,
  formData: FormData
): Promise<ActionState> {
  // 1. Verify admin role
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // 2. Validate with Zod
  const rawData = {
    sucursal_id: formData.get("sucursal_id"),
    cliente_id: formData.get("cliente_id"),
    descripcion_problema: formData.get("descripcion_problema"),
  };

  const result = folioSchema.safeParse(rawData);
  if (!result.success) {
    const flattened = z.flattenError(result.error);
    return { fieldErrors: flattened.fieldErrors };
  }

  // 3. Validate user assignment
  const userIds = formData.getAll("usuarios") as string[];
  if (userIds.length === 0) {
    return { error: "Debe asignar al menos un tecnico al folio" };
  }

  // 4. Update folio table (do NOT update estatus in Phase 2)
  const { error: updateError } = await supabase
    .from("folios")
    .update({
      sucursal_id: result.data.sucursal_id,
      cliente_id: result.data.cliente_id,
      descripcion_problema: result.data.descripcion_problema,
    })
    .eq("id", id);

  if (updateError) {
    return {
      error: "Error al actualizar el folio: " + updateError.message,
    };
  }

  // 5. Reassign users: delete existing, insert new
  const { error: deleteError } = await supabase
    .from("folio_asignados")
    .delete()
    .eq("folio_id", id);

  if (deleteError) {
    return {
      error:
        "Error al actualizar asignaciones: " + deleteError.message,
    };
  }

  const assignments = userIds.map((uid) => ({
    folio_id: id,
    usuario_id: uid,
  }));

  const { error: assignError } = await supabase
    .from("folio_asignados")
    .insert(assignments);

  if (assignError) {
    return {
      error:
        "El folio fue actualizado pero hubo un error al reasignar usuarios: " +
        assignError.message,
    };
  }

  // 6. Revalidate and redirect
  revalidatePath("/admin/folios");
  redirect("/admin/folios");
}
