"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ordenServicioSchema } from "@/lib/validations/ordenes-servicio";
import { z } from "zod";
import type { ActionState } from "@/types/actions";

// ── Create Orden de Servicio ──────────────────────────────────────────────

export async function createOrdenServicio(
  _prevState: ActionState | null,
  formData: FormData
): Promise<ActionState> {
  // 1. Verify admin role
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // 2. Validate with Zod
  const rawData = {
    sucursal_id: formData.get("sucursal_id"),
    cliente_id: formData.get("cliente_id"),
    descripcion_problema: formData.get("descripcion_problema"),
  };

  const result = ordenServicioSchema.safeParse(rawData);
  if (!result.success) {
    const flattened = z.flattenError(result.error);
    return { fieldErrors: flattened.fieldErrors };
  }

  // 3. Validate user assignment
  const userIds = formData.getAll("usuarios") as string[];
  if (userIds.length === 0) {
    return { error: "Debe asignar al menos un tecnico a la orden de servicio" };
  }

  // 4. Insert orden de servicio (numero_orden auto-generated by DB trigger)
  const { data: orden, error: ordenError } = await supabase
    .from("ordenes_servicio")
    .insert({
      sucursal_id: result.data.sucursal_id,
      cliente_id: result.data.cliente_id,
      descripcion_problema: result.data.descripcion_problema,
    })
    .select("id")
    .single();

  if (ordenError) {
    return { error: "Error al crear la orden de servicio: " + ordenError.message };
  }

  // 5. Insert user assignments
  const assignments = userIds.map((uid) => ({
    orden_servicio_id: orden.id,
    usuario_id: uid,
  }));

  const { error: assignError } = await supabase
    .from("orden_asignados")
    .insert(assignments);

  if (assignError) {
    return {
      error:
        "La orden fue creada pero hubo un error al asignar usuarios: " +
        assignError.message,
    };
  }

  // 6. Insert equipment assignments
  const equipoIds = formData.getAll("equipos") as string[];
  if (equipoIds.length > 0) {
    const equipoAssignments = equipoIds.map((eid) => ({
      orden_servicio_id: orden.id,
      equipo_id: eid,
      added_by: user.id,
    }));

    const { error: equipoError } = await supabase
      .from("orden_equipos")
      .insert(equipoAssignments);

    if (equipoError) {
      return {
        error:
          "La orden fue creada pero hubo un error al asignar equipos: " +
          equipoError.message,
      };
    }
  }

  // 7. Revalidate and redirect
  revalidatePath("/admin/ordenes-servicio");
  redirect("/admin/ordenes-servicio");
}

// ── Update Orden de Servicio ──────────────────────────────────────────────

export async function updateOrdenServicio(
  id: string,
  _prevState: ActionState | null,
  formData: FormData
): Promise<ActionState> {
  // 1. Verify admin role
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // 2. Validate with Zod
  const rawData = {
    sucursal_id: formData.get("sucursal_id"),
    cliente_id: formData.get("cliente_id"),
    descripcion_problema: formData.get("descripcion_problema"),
  };

  const result = ordenServicioSchema.safeParse(rawData);
  if (!result.success) {
    const flattened = z.flattenError(result.error);
    return { fieldErrors: flattened.fieldErrors };
  }

  // 3. Validate user assignment
  const userIds = formData.getAll("usuarios") as string[];
  if (userIds.length === 0) {
    return { error: "Debe asignar al menos un tecnico a la orden de servicio" };
  }

  // 4. Update ordenes_servicio table
  const { error: updateError } = await supabase
    .from("ordenes_servicio")
    .update({
      sucursal_id: result.data.sucursal_id,
      cliente_id: result.data.cliente_id,
      descripcion_problema: result.data.descripcion_problema,
    })
    .eq("id", id);

  if (updateError) {
    return {
      error: "Error al actualizar la orden de servicio: " + updateError.message,
    };
  }

  // 5. Reassign users: delete existing, insert new
  const { error: deleteError } = await supabase
    .from("orden_asignados")
    .delete()
    .eq("orden_servicio_id", id);

  if (deleteError) {
    return {
      error:
        "Error al actualizar asignaciones: " + deleteError.message,
    };
  }

  const assignments = userIds.map((uid) => ({
    orden_servicio_id: id,
    usuario_id: uid,
  }));

  const { error: assignError } = await supabase
    .from("orden_asignados")
    .insert(assignments);

  if (assignError) {
    return {
      error:
        "La orden fue actualizada pero hubo un error al reasignar usuarios: " +
        assignError.message,
    };
  }

  // 6. Reassign equipment: delete existing, insert new
  const { error: deleteEquipoError } = await supabase
    .from("orden_equipos")
    .delete()
    .eq("orden_servicio_id", id);

  if (deleteEquipoError) {
    return {
      error:
        "Error al actualizar equipos: " + deleteEquipoError.message,
    };
  }

  const equipoIds = formData.getAll("equipos") as string[];
  if (equipoIds.length > 0) {
    const equipoAssignments = equipoIds.map((eid) => ({
      orden_servicio_id: id,
      equipo_id: eid,
      added_by: user.id,
    }));

    const { error: equipoError } = await supabase
      .from("orden_equipos")
      .insert(equipoAssignments);

    if (equipoError) {
      return {
        error:
          "La orden fue actualizada pero hubo un error al reasignar equipos: " +
          equipoError.message,
      };
    }
  }

  // 7. Revalidate and redirect
  revalidatePath("/admin/ordenes-servicio");
  redirect("/admin/ordenes-servicio");
}

// ── Add Equipment to Orden ──────────────────────────────────────

export async function addEquipmentToOrden(
  ordenId: string,
  equipoId: string
): Promise<ActionState> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  const { error } = await supabase
    .from("orden_equipos")
    .upsert(
      { orden_servicio_id: ordenId, equipo_id: equipoId, added_by: user.id },
      { onConflict: "orden_servicio_id,equipo_id" }
    );

  if (error) {
    return { error: "Error al agregar equipo a la orden: " + error.message };
  }

  revalidatePath(`/admin/ordenes-servicio/${ordenId}`);
  return { success: true, message: "Equipo agregado a la orden" };
}

// ── Remove Equipment from Orden ─────────────────────────────────

export async function removeEquipmentFromOrden(
  ordenId: string,
  equipoId: string
): Promise<ActionState> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.app_metadata?.rol !== "admin") {
    return { error: "No autorizado" };
  }

  // Check if equipment has report entries under this orden
  const { data: reportEntries } = await supabase
    .from("reporte_equipos")
    .select("id, reportes!inner(orden_servicio_id)")
    .eq("equipo_id", equipoId)
    .eq("reportes.orden_servicio_id", ordenId)
    .limit(1);

  if (reportEntries && reportEntries.length > 0) {
    return {
      error:
        "No se puede quitar este equipo porque tiene reportes asociados en esta orden.",
    };
  }

  const { error } = await supabase
    .from("orden_equipos")
    .delete()
    .eq("orden_servicio_id", ordenId)
    .eq("equipo_id", equipoId);

  if (error) {
    return { error: "Error al quitar equipo de la orden: " + error.message };
  }

  revalidatePath(`/admin/ordenes-servicio/${ordenId}`);
  return { success: true, message: "Equipo quitado de la orden" };
}
